### ISSUE TITLE
$in query stopped working in 1.6.1

### ISSUE THREAD

**Issue by larslorenzen** [fakemongo/fongo#100]
I have a test which does a query like this:
db.translations.find({ "lang" : "de" , "platform" : { "$in" : [ { "$ref" : "platforms" , "$id" : "demo"}]}})
The test worked fine in 1.5.10 but stopped working in 1.6.1 (no results from that query).

        DBCollection translations = db.getCollection("translations");
        BasicDBList platforms = new BasicDBList();
        platforms.add(new DBRef("platforms", "demo"));
        DBObject query = new BasicDBObject("lang", "de").append("platform", new BasicDBObject("$in", platforms));
        DBCursor cursor = translations.find(query);
        cursor.hasNext(); // <- true in 1.5.10, false in 1.6.1

**Comment by twillouer** [comment]
Thanks for the report.

$in change in 1.6.1, so try 1.6.0 and it will works correctly.
