### ISSUE TITLE
Insert error on Mongo Java driver 3.x ... "IllegalArgumentException  ... cluster can not be null"

### ISSUE THREAD

**Issue by colmmcdonnell** [fakemongo/fongo#101]
I'm getting an IllegalArgumentException when calling DBCollection.insert() ...

````
java.lang.IllegalArgumentException: cluster can not be null
	at com.mongodb.assertions.Assertions.notNull(Assertions.java:34)
	at com.mongodb.binding.ClusterBinding.<init>(ClusterBinding.java:46)
	at com.mongodb.Mongo.getReadWriteBinding(Mongo.java:709)
	at com.mongodb.Mongo.getWriteBinding(Mongo.java:701)
	at com.mongodb.Mongo.execute(Mongo.java:740)
	at com.mongodb.Mongo$2.execute(Mongo.java:725)
	at com.mongodb.DBCollection.executeWriteOperation(DBCollection.java:326)
	at com.mongodb.DBCollection.insert(DBCollection.java:322)
````

Setup, versions etc as follows:

* Fongo: 1.6.0 
* Mongo Java Driver: 3.0.0-beta3 (http://mvnrepository.com/artifact/org.mongodb/mongo-java-driver/3.0.0-beta3)

Reproduction case:

````
    @Test(expected = IllegalArgumentException.class)
    public void cannotInsertUsingFongoOnePointSixWithMongoDriverVersionThreeDotX() {
        Mongo mongo = new Fongo("test").getMongo();
        
        DB db = mongo.getDB("foo");

        DBCollection collection = db.getCollection("bar");

        // insert anything ... will barf with "cluster can not be null"
        collection.insert(new BasicDBObject("a", "b"));
    }
````

If I downgrade my mongo-java-driver to 2.13.0-rc2 then the problem disappears so this looks like an incompatability between Fongo 1.6.0 and Mongo's 3.x Java driver.

**Comment by dazraf** [comment]
Hi, this is definitely an issue for us also.

**Comment by twillouer** [comment]
Yes, fongo is only compatible with 2.1X drivers.

I will try to make it compatible with 3.x drivers this week-end if I had time

**Comment by colmmcdonnell** [comment]
@twillouer, thanks

**Comment by dazraf** [comment]
Thanks very much :-)

**Comment by twillouer** [comment]
Tests run: 494, Failures: 4, Errors: 334, Skipped: 20

works in progress

**Comment by dazraf** [comment]
Nice work!

**Comment by colmmcdonnell** [comment]
@twillouer thanks

**Comment by twillouer** [comment]
This is far away to be finished, but if you want to try againts the "v3" branch, feedbacks are welcome :)

**Comment by dazraf** [comment]
Thanks @twillouer. Will try it first thing Monday morning.

**Comment by twillouer** [comment]
any news ?

**Comment by colmmcdonnell** [comment]
@twillouer apologies, busy week, will give it a whirl over the weekend or early next week

Thanks

**Comment by colmmcdonnell** [comment]
@twillouer: I have built fongo from your v3 branch and run our full test suite against v3.0.0-beta3 of the Mongo Java driver and it's all green. Looking good, thanks.

**Comment by dtracers** [comment]
I just wanted to let you guys know that the official mongo v3.0.0 driver is out of beta.

**Comment by twillouer** [comment]
do you want a release for this branch ?

**Comment by dtracers** [comment]
I would enjoy a release.  But it is nothing urgent for me personally.  I was trying to build it just to see if it would work but I had problems with my computer.
Also I hope my previous comment did not come off as passive aggressive (reading it back I can see that interpretation...)  I just meant that because it is out of beta it might need to be retested.  :+1:

**Comment by twillouer** [comment]
no, no, don't worry.

Will check if I can close a bug or two before :)

**Comment by dazraf** [comment]
Hi,
Sorry for being away for a while (had a few things to sort out).
Very grateful for all your work. 
I've been testing the latest version for v3. 
Have some news (some not so good, sorry):
1. Mongo driver version 3.0.0 final has been released. There's a couple of breaking changes. I can provide a patch for this.
2. Did you know that in v3.0.0 driver, Mongo.getDB is deprecated? Clients are supposed to use the MongoClient.getDatabase. In effect, DB and DBCollection are deprecated. MongoDatabase and MongoCollection are the new kids in town.
3. AFAIK the current fongo v3 doesn't support any 3.0.0 APIs. Which is a bit of deal-breaker at the moment as we want to upgrade to 3.0 to use the new Async API.

I'll work out how we could implement MongoDatabase and MongoCollection on the existing classes ... perhaps it's possible. But the API is dramatically different, having re-read this a few times: 
http://mongodb.github.io/mongo-java-driver/3.0/

Sorry for the bad news. Would like to see v3 progress very much.

**Comment by dtracers** [comment]
maybe we could make an alpha release using the deprecated values?
I'm planning on using a two step process.

Where the first step is upgrading to mongo 3.0 but leaving in the deprecated methods and ensure that everything else works.
Then move to the new api's later.

**Comment by twillouer** [comment]
if you have time to test agains the V3 branch, I can release a 2.0.0 version for "old api" and provide a better implem after.

Btw, the new api seems hard to implement, they have better classes, with better usage of private field, who let things more difficult to mock.

**Comment by dtracers** [comment]
I will work on that.

I had trouble last time but that was due to me not knowing how to pull the v3 branch via maven.  I will test it today to see if at least basic functionality works and I will list what apis I use too.

**Comment by twillouer** [comment]
thanks.

btw, @dazraf , you're rude with me :P

**Comment by dtracers** [comment]
So to pull the code down (since I am using fongo as a maven repository)
I am using a tool called jitpack (https://jitpack.io)

and I am pulling down this commit:
66a66f19c8b4d68f9c1a725d5ee10b029b372180

but it is not building because of an error:
(which can be seen here)
https://jitpack.io/com/github/fakemongo/fongo/66a66f19c8b4d68f9c1a725d5ee10b029b372180/build.log

specifically:
```
[ERROR] /build/src/test/java/com/github/fakemongo/impl/index/IndexTest.java:[60,4] cannot access java.nio.file.Path
class file for java.nio.file.Path not found
    assertThat(resultObject).isEqualTo(sourceObject);
```

If this is not an error on your side I will create an issue with the jitpack people so they can fix it on their side.
I am currently cloning the repository to build it on my computer (but that may take a while)

**Comment by dtracers** [comment]
Looking at the pom I see it compiles to jvm 1.6 but fails trying to use Path which did not exist until 1.7

In the scala plugin it has the settings of 1.6
```
 <javacArgs>
                        <javacArg>-source</javacArg>
                        <javacArg>1.6</javacArg>
                        <javacArg>-target</javacArg>
                        <javacArg>1.6</javacArg>
                    </javacArgs>
                    <jvmArgs>
                        <jvmArg>-Xms64m</jvmArg>
                        <jvmArg>-Xmx1024m</jvmArg>
                        <!--jvmArg>-Dscala.timings=true</jvmArg -->
                    </jvmArgs>
                    <args>
                        <arg>-target:jvm-1.6</arg>
                        <arg>-unchecked</arg>
                        <arg>-deprecation</arg>
                        <arg>-feature</arg>
                    </args>
```

I believe this could be the issue but it does compile on my computer.

**Comment by dtracers** [comment]
https://travis-ci.org/fakemongo/fongo/builds/59119764

It appears that #104 breaks in the jdk1.6 environment now.

**Comment by twillouer** [comment]
@dtracers java 1.6 is back (but, seriously, java 7 is EOL this month !)

**Comment by twillouer** [comment]
@dazraf point 1 and 2 handled (I hope), point 3 in progress.

**Comment by hinews** [comment]
I've the same problem but after upgrade works good with fongo 2.0

**Comment by twillouer** [comment]
@hinews same stacktrace ?!
Are you with mongodb drivers 3.0.1 or with 2.13.0 ?

**Comment by twillouer** [comment]
@dazraf @dtracers any news ?

**Comment by hinews** [comment]
@twillouer The same stacktrace was before upgrade to fongo 2.0. Mongo driver 3.0.1 
At this moment all fine

**Comment by dtracers** [comment]
Hi Unfortunately I did not get this until now but I can not work on it this summer (internship).
I know that as long as the config said it was supports java 1.6 but the code itself used 1.7 only features we will not be be able to build it.

**Comment by twillouer** [comment]
Right, the part with "Geo". I didn't notice.

But you can use the binary for fongo 2.0.1 ?

**Comment by twillouer** [comment]
@dtracers sorry, I miss myself : all is fine on java 6 on my computer, what problem do you have (on v3 branch)
