### ISSUE TITLE
Regression on aggregation in 1.6.x

### ISSUE THREAD

**Issue by tkruse** [fakemongo/fongo#104]
HI,

We face a regression when upgrading from 1.5.10 to 1.6.1. 
I have a project to reproduce:

```
git clone git@github.com:tkruse/fongobug.git
cd fongobug
./gradlew test -PfongoVersion='1.5.10'
./gradlew test -PfongoVersion='1.6.0'
```

For me, test with 1.5.10 passes, whereas 1.6.x breaks:
```
repositories.StatisticRepositoryImplTest > testGetAllStatistics FAILED
    java.lang.AssertionError: 
    Expected: <2L>
         but: was <5L>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:865)
        at org.junit.Assert.assertThat(Assert.java:832)
        at repositories.StatisticRepositoryImplTest.testGetAllStatistics(StatisticRepositoryImplTest.java:77)
```

What breaks is the Aggregation with a filter:
```
 final TypedAggregation<Vacancy> agg = newAggregation(Vacancy.class,
                match(
                    where(Vacancy.PersistenceInfo.VACANCY_STATUS).is(Vacancy.VacancyStatus.VACANT)
                ),
                unwind(Vacancy.PersistenceInfo.APPLICATIONS), project(Vacancy.PersistenceInfo.APPLICATIONS),
                match(
                    where(APPLICATION_MESSAGES_FIELD).not().elemMatch(
                        new Criteria().orOperator(
                            where(CLASS_FIELD).is(FooMessage.class.getName()),
                            where(CLASS_FIELD).is(BarMessage.class.getName())
                        )
                    )
                ),
group(APPLICATION_TYPE_FIELD).count().as(CountAggregationResult.PersistenceInfo.COUNT));
```

the matcher in the middle with not().elemMatch(...) does not seem to work anymore with 1.6.x

Sorry if example is still convoluted.

**Comment by tkruse** [comment]
Using Ubuntu Linux and oracle java JDK 7

**Comment by twillouer** [comment]
Hi,

sorry for that, but I don't really understand the problem :-(

can you bring me a set of test in mongodb ?

And can you try against the 1.6.1 version ?
Thanks !

**Comment by tkruse** [comment]
Did you try to reproduce as I said?
Using my github project and gradle? 1.6.1 has the same problem, can be easily checked:
```
git clone git@github.com:tkruse/fongobug.git
cd fongobug
./gradlew test -PfongoVersion='1.6.1'
```
Not sure what else I could give you.But I can make the code simpler maybe.

**Comment by tkruse** [comment]
Ok, sample code at github is much simpler now. I can next provide a MongoDB Configuration so that we can look at the raw data in database.

**Comment by tkruse** [comment]
So, DB sample is:
```
{ "_id" : ObjectId("550ed67144ae297b69c6e190"), "_class" : "domain.Vacancy", "applications" : [ { "_id" : null, "messages" : [ { "_class" : "domain.FooMessage" } ] } ] }
```

And query that works in 1.5.10 but not 1.6.x is:
```
template.find(Query.query(where(APPLICATION_MESSAGES_FIELD).not().elemMatch(
                new Criteria().orOperator(
                        where("_class").is("domain.FooMessage")
                )
        )), Vacancy.class);
```

**Comment by tkruse** [comment]
github project now contains spring-boot populator to get some data into test mongodb

**Comment by twillouer** [comment]
I'm not fluent with gradle, how can I test against a local artefact ?

:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestJava

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':testCompile'.
> Could not find com.github.fakemongo:fongo:1.6.3-SNAPSHOT.
  Required by:
      :fongobug:unspecified
> Could not find com.github.fakemongo:fongo:1.6.3-SNAPSHOT.
  Required by:
      :fongobug:unspecified > com.lordofthejars:nosqlunit-mongodb:0.7.9

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

(the artefact is in maven repository on my machine)

**Comment by tkruse** [comment]
Use
```
repositories {
    jcenter()
    mavenLocal()
}
```
mavenLocal() will look for an artifact in your local maven repo.

**Comment by twillouer** [comment]
Will try again.

I think the problem comes from https://github.com/fakemongo/fongo/commit/b9d1dd31e1af6bbed5f877cbf61d0dc52dbe16d3

I'll keep you informed

**Comment by twillouer** [comment]
Hi,

it's works on my machine :)

```
BUILD SUCCESSFUL

Total time: 16.947 secs
./gradlew test  21,05s user 1,76s system 129% cpu 17,600 total
```

can you test against 1.6.3-SNAPSHOT ?

**Comment by tkruse** [comment]
I am on a long holiday, cannot test again. Thanks anyway.

**Comment by twillouer** [comment]
Not a problem. Give me a feedback when you come back, and enjoy your hollidays :)
