### ISSUE TITLE
Test MongoExceptions

### ISSUE THREAD

**Issue by scho** [fakemongo/fongo#106]
I'd like to test exceptions thrown by the mongo driver. 

E.g. in my DAO I want to catch the `MongoExecutionTimeoutException` and have some kind of failover behaviour. Is there a way to tell my `Fongo` instance that it should throw an exception instead of performing the operation?

**Comment by dtracers** [comment]
you could mock fongo.  (a double mock!)

**Comment by twillouer** [comment]
Hi,

there is no way from now to do things like this, but perhaps we can add this feature.

Do you have a use case ?
It's only on cursor ?

@dtracers is right, if you have mockito, perhaps the best way is to "spy" your instance and answer a MongoTimeoutException ?
