### ISSUE TITLE
Not possible to specify same attribute multiple times in aggregates?

### ISSUE THREAD

**Issue by yannickdeturck** [fakemongo/fongo#107]
I am using 1.6.2.

My documents have the following form:
```
> db.logRecord.findOne()
{
	"_id" : ObjectId("552f80885b663d29f1026376"),
	"startDate" : ISODate("2015-03-30T00:00:00Z"),
	"endDate" : ISODate("2015-03-30T00:05:00Z"),
	"message" : "hi there"
}
```

And given following snippet:
```
String json = "[" +
					"{ \"$project\": { "+
					"a: \"$startDate\", " +
					"b: \"$startDate\", " +
					"c: \"$startDate\", " +
					"d: \"$endDate\" " +
					"}}" +
					"]";

BasicDBList pipeline = (BasicDBList)com.mongodb.util.JSON.parse(json);
BasicDBObject aggregation = new BasicDBObject("aggregate", "logRecord")
					.append("pipeline", pipeline);
CommandResult commandResult = mongoTemplate.executeCommand(aggregation);
```
In the result I'm only receiving a value for the id-, c-field and d-field. It seems like "a" and "b" are being ignored because it has the same field as value as "c". If I were to remove "c" form the JSON String then "b" will be available in the result but not "a".

Point of doing this is because I want to lookup all unique dates based on year, month and day (ignoring hours, minutes, etc) and before grouping I want to do a $project to retrieve the year, month and day.

If I try to reproduce this with a real Mongo instance I do not experience this issue.

**Comment by twillouer** [comment]
can you check against the master branch plz ?

**Comment by yannickdeturck** [comment]
Just tested. I can confirm that all fields are available in the result now.
Thanks!
