### ISSUE TITLE
scope not supported in mapReduce

### ISSUE THREAD

**Issue by hoegertn** [fakemongo/fongo#112]
It seems that the scope is not supported in map reduce jobs. The scope allows to share state across java,map,reduce and finalize function.

**Comment by twillouer** [comment]
Right,

wich version of mongodb drivers do you use ?
you need this for fongo 1.6 or fongo 2.X ?

**Comment by hoegertn** [comment]
I am using MongoDB Driver 3.0.1 with Fongo 2.0.0 (https://github.com/taimos/spring-dao-mongo)

**Comment by twillouer** [comment]
Hi,

can you try against the v3 branch ?

**Comment by hoegertn** [comment]
Seems to work. Any ETA of the release?

**Comment by twillouer** [comment]
When you need :)

**Comment by hoegertn** [comment]
I'd like to see this when possible. I will update my MongoDB library and use it in a current project. As i use fongo for unit tests I can only use MongoDB functionality in my software that is supported by fongo.

**Comment by twillouer** [comment]
@hoegertn done :)

**Comment by hoegertn** [comment]
thx
