### ISSUE TITLE
Lots of dependencies from com.mongodb can not be found anywhere

### ISSUE THREAD

**Issue by palmtale** [fakemongo/fongo#113]
Could you guys please inform me how to construct Fongo? See the code below: 
 public Fongo(String name) {
        this.name = name;
        this.serverAddress = new ServerAddress(new InetSocketAddress(ServerAddress.defaultHost(), ServerAddress.defaultPort()));
        this.mongo = this.createMongo();
    }
But where is the ServerAddress (com.mongodb.ServerAddress)? in mongodb-driver-3.0.1.jar or any other dependencies.

**Comment by twillouer** [comment]
Hi,

yes, you need the real mongodb drivers.

2.12.X for fongo 1.6 or 3.0.1 for fongo 2.0

**Comment by palmtale** [comment]
Yep, It's OK for the fongo1.6 - mongo-java-driver2.12.5
But for fongo2.0.0 it's not OK since mongo-java-driver3.0.1 dropped import com.mongodb.ReadPreference;
com.mongodb.ServerAddress;
com.mongodb.WriteConcern;

**Comment by twillouer** [comment]
I'm not sure to undersand,

I use 
```
        <dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongo-java-driver</artifactId>
            <version>3.0.1</version>
            <scope>provided</scope>
        </dependency>
```

in three projects and I don't have any problem.
And ReadPreference is in mongo-java-driver, same fofr ServerAddress and WriteConcern.

Do you use maven ?

**Comment by palmtale** [comment]
Well sorry, there's another version , coordinate is "org.mongodb:mongo-driver:3.0.1"
