### ISSUE TITLE
Fongo find and Update return document After not work

### ISSUE THREAD

**Issue by yvladimirov** [fakemongo/fongo#114]
Fongo 2.0
Mongo 3.0.1
Fongo find and Update return document After not work. Return Before document

        MongoClient mongoClient = new Fongo("").getMongo();
        MongoCollection<Document> testCollection = mongoClient.getDatabase("test").getCollection("test");

        testCollection.insertOne(new Document("updateField", 1));

        Document document = testCollection.find(eq("updateField", 1)).first();

        assertEquals(1,document.get("updateField"));

        document= testCollection.findOneAndUpdate(eq("updateField", 1),new Document("updateField",2),new FindOneAndUpdateOptions().returnDocument(ReturnDocument.BEFORE));

        assertEquals(1,document.get("updateField"));

        document = testCollection.find(eq("updateField", 2)).first();
        assertEquals(2,document.get("updateField"));

        document= testCollection.findOneAndUpdate(eq("updateField", 2),new Document("updateField",3),new FindOneAndUpdateOptions().returnDocument(ReturnDocument.AFTER));

        //TODO Return old value
        assertEquals(3,document.get("updateField"));

**Comment by twillouer** [comment]
Hi, corrected in v3 branch if you want to try
