### ISSUE TITLE
Error:(54, 50) java: cannot access com.mongodb.operation.OperationExecutor   class file for com.mongodb.operation.OperationExecutor not found

### ISSUE THREAD

**Issue by tjmcclure0501** [fakemongo/fongo#115]
Using fongo with Spring data I get the above compilation error.  Below is the code:
   @Bean
    @Override
    public Mongo mongo() throws Exception {

        //ServerAddress serverAdress = new ServerAddress("localhost", 27017);
        //MongoCredential credential = MongoCredential.createMongoCRCredential("moez","tuto","secret".toCharArray());
        //Do not use new Mongo(), is deprecated.
        //Mongo mongo = new MongoClient(serverAdress,Arrays.asList(credential));
        //Mongo mongo = new MongoClient(serverAdress);
        //mongo.setWriteConcern(WriteConcern.SAFE);
        //return mongo;
        return new Fongo("trade-test").getMongo();
    }

**Comment by twillouer** [comment]
Hi,

witch version of mongodb-java-drivers do you use ?
and same question for fongo ?

**Comment by twillouer** [comment]
Hi, any news ?

**Comment by kajsa** [comment]
For posterity - I got the same error when accidentally mixing mongo major versions. In my case, I had fongo 2.0.6, but spring-boot-starter-data-mongodb was pulling in a 2.x version of the mongodb-java-drivers (where a 3.x version was needed).
