### ISSUE TITLE
Loss field type

### ISSUE THREAD

**Issue by yvladimirov** [fakemongo/fongo#116]
Fongo 2.0.1
Mongodriver 3.0.1

Hello, If I saved field Long type and find this document it's Ok but if I use findOneAndUpdate returning document return Integer type

        Document d = new Document("test", 1l);
        db.getCollection("test").insertOne(d);
        d = db.getCollection("test").find(new Document("test", 1l)).first();
        assertEquals(1l, d.get("test"));
        d = db.getCollection("test").findOneAndUpdate(new Document("test", 1l), new Document("$set", new Document("test", 1l)));

        assertEquals(1l, d.get("test"));//java.lang.Long<1> but was: java.lang.Integer<1>

**Comment by twillouer** [comment]
Right,

thanks for the report.

The "old way" to convert DBObject to BsonDocument was to parse JSon. And I loose types.

Now, I think it's good
