### ISSUE TITLE
Modified count is only available when connected to MongoDB 2.6 servers or above

### ISSUE THREAD

**Issue by smaant** [fakemongo/fongo#117]
Hello. I've found some strange behaviour in fongo 2.0.1 with mongo 3.0.x driver. Simple example:
```java
@Test
public void test() {
  MongoCollection<Document> col = fongoRule.newMongoCollection("test");
  col.insertOne(new Document("key", "value"));
  UpdateResult result = col.updateOne(eq("key", "value"), new Document("$set", new Document("key", "value2")));
  System.out.println(result.getModifiedCount());
}
```
Result will be:
```
java.lang.UnsupportedOperationException: Modified count is only available when connected to MongoDB 2.6 servers or above.
	at com.mongodb.client.result.UpdateResult$AcknowledgedUpdateResult.getModifiedCount(UpdateResult.java:117)
```
Do I understand correctly that this new part of mongo api is not supported yet?

**Comment by twillouer** [comment]
Right, thanks for the report.

Can you check against the v3 branch with mvn clean install -DskipTests and report me other problem ?

**Comment by smaant** [comment]
I did, 'modified count' issue is gone, but I found another one:
```java
  @Test
  public void test() {
    MongoCollection<Document> col = fongoRule.newMongoCollection("test");
    col.insertOne(new Document("key", "value"));
    col.findOneAndReplace(eq("key", "other_value"), new Document("key", "value2"));
  }
```

**Comment by twillouer** [comment]
Thanks.
Handle in the v3 branch. Don't hesitate if you have another issues (or if you want a version)

**Comment by smaant** [comment]
Thank you too! I'll let you know if I run into something else. I'm not in a hurry, so if you're planning to release a new version for v3 in some not very far future - it'll be fine then.
