### ISSUE TITLE
DBCollection.drop() removes indexes on other collections

### ISSUE THREAD

**Issue by wbdarby** [fakemongo/fongo#119]
Re-opening #91 - that closed an issue with dropIndexes(), but the bug was originally written about an issue with DBCollection.drop().

The FongoDBCollection.drop calls _dropIndexes(), which is implemented as:

protected synchronized void _dropIndexes() {
    final List<DBObject> indexes = fongoDb.getCollection("system.indexes").find().toArray();
    // Two step for no concurrent modification exception
    for (final DBObject index : indexes) {
      final String indexName = index.get("name").toString();
      if (!ID_NAME_INDEX.equals(indexName)) {
        dropIndexes(indexName);
      }
    }
  }

The fongoDb.getCollection("system.indexes").find().toArray();
returns all indexes in the DB and deletes all of these that are not '_id', even those not related to the collection being dropped.

This should be changed to locate only the indexes related to the collection.

Here's a small test case that fails with Fongo 1.5.10 & likely 2.0.1 since the code is the same.
The second assertEquals fails

  @Test
  @UsingDataSet(locations="EmptyDataTest.json", loadStrategy=LoadStrategyEnum.CLEAN_INSERT)
  public void test() throws InterruptedException {
    // Given
    DB db = mongoClient.getDB( DB_NAME );
    DBCollection col1 = db.getCollection( "coll1" );
    DBCollection col2 = db.getCollection( "coll2" );
    col1.createIndex(new BasicDBObject("date", 1));
    col2.createIndex(new BasicDBObject("date", 1));
    
    assertEquals(2, col2.getIndexInfo().size());

    // When
    col1.drop();
    
    // Then
    assertEquals(2, col2.getIndexInfo().size());
  }

**Comment by twillouer** [comment]
Hi,

I try a test : https://github.com/fakemongo/fongo/commit/63e185e801625ceeab2f7fbb42dcc6ef79291bd0 but all is fine.

Where am I wrong ?

**Comment by twillouer** [comment]
I close the issue, reopen it if you need
