### ISSUE TITLE
Supporting 2dsphere indexes.

### ISSUE THREAD

**Issue by rigelbm** [fakemongo/fongo#12]
There is no current support for 2dsphere indexes. Only legacy coordinate pair. I managed to get it "working" with the following changes:

GeoUtil.getLatLong(Object): add decoding option for GeoJSON format.
IndexAbstract.prepareKeys(DBObject): Also change 2dsphere indexes into "1"
IndexFactory.getGeoKey(DBObject): Recognize 2dsphere indexes as a GeoKey.

That was enough to get Fongo to add 2dsphere indexes. As for query operations, it only works if I issue a DB.command operation. DBCollection.query returns the result unordered.

How it is working now:

// This crashes with message "Projection `my_key' has a values that Fongo doesn't 
// know how to handle: 2dsphere (java.lang.String)"
collection.ensureIndex(new BasicDBObject("my_key", "2dsphere")); 

// This returns an empty list
collection.find(BasicDBObjectBuilder.start().push("my_key").push("$nearSphere")
    .add("$geometry", GeoJSON.toDBObject(myPoint)).pop().pop().get());

// GeoJSON.toDBObject(Point) returns { type: "Point", coordinates: [long, lat] }

How it works after the workaround:

// This works
collection.ensureIndex(new BasicDBObject("my_key", "2dsphere")); 

// This returns an unordered list of points
collection.find(BasicDBObjectBuilder.start().push("my_key").push("$nearSphere")
    .add("$geometry", GeoJSON.toDBObject(myPoint)).pop().pop().get());

// This works
db.command(BasicDBObjectBuilder.start().add("geoNear", "my_collection")
    .add("near", GeoJSON.toDBObject(myPoint).add("spherical", true)).get("results");

**Comment by twillouer** [comment]
@rigelbm I think most of your cases are correctly handled now :)
