### ISSUE TITLE
fongoDBCollection.rename("newname") results in CommandFailureException

### ISSUE THREAD

**Issue by g1l3sp** [fakemongo/fongo#125]
Attempting to rename a collection using fongo throws an exception:

    com.mongodb.CommandFailureException: { "serverUsed" : "localhost:27017" , "ok" : 0 , "errmsg" : "no such cmd: renameCollection"}
    	at com.mongodb.CommandResult.getException(CommandResult.java:76)
    	at com.mongodb.CommandResult.throwOnError(CommandResult.java:140)
    	at com.mongodb.DBCollection.rename(DBCollection.java:1314)
     	...

This method appears to be unimplemented (the generated command is unhandled anyway).  It'd be handy if it worked, and without knowing anything about the internals of fongo, it seems like it might be an easy one to add :-)

**Comment by twillouer** [comment]
Hi,

wich version of fongo and mongodb do you use ?

**Comment by g1l3sp** [comment]
Here are the maven coordinates for what I think you are asking for:
com.github.fakemongo:fongo:1.6.2
org.mongodb:mongo-java-driver:2.13.0

Does that cover it?

**Comment by twillouer** [comment]
Perfect, will take a look.

For my own knowledge, what's the purpose of "renaming a collection" in an Unit Test ?

**Comment by twillouer** [comment]
You can test against the "master" branch :)

**Comment by g1l3sp** [comment]
Thank you!  I'll check it out when I get the chance.

WRT to the purpose, we're unit testing data transformation scripts, some of which create temporary collections and then rename them into place.  Our tests do the following:
- take sample input documents and store them in fongo
- run the transformation scripts against them, storing the transformed documents into fongo
- compare expected results against what got stored
