### ISSUE TITLE
com.mongodb.FongoMongoCollection.drop throws Exception

### ISSUE THREAD

**Issue by Chaosdevice** [fakemongo/fongo#126]
'java.lang.RuntimeException: json can't serialize type : class org.bson.BsonString' error is generated by the following code using the version 2.0.1:

        db = fongoRule.getDatabase("test");
        MongoCollection<Document> collection = db.getCollection("testcol");
        collection.drop();

Note,  we were encountering this exception when trying to test our code that first drops a collection then recreates and collection to ensure it is empty.

**Comment by twillouer** [comment]
Hi, thanks for the report.

You can test against the "v3" branch :)
