### ISSUE TITLE
Inconsistent behaviour of $all operator

### ISSUE THREAD

**Issue by dario-campagna** [fakemongo/fongo#129]
When querying for a document using the `$all` operator and the empty array as parameter, MongoDB (version 3.0.4) returns `null`, as shown in the following example.

```
> db.collection.insert({"_id": 1, "tags": ["mongo", "javascript"]})
WriteResult({ "nInserted" : 1 })
> db.collection.findOne({tags: {$all: []}})
null
```

However, the same query performed against fongo does not return `null`. This can be verified running the following test (we added it to the FongoTest class on the master branch and it fails).

```java
@Test
public void testFindAllWithEmptyList() {
  DBCollection collection = newCollection();
  collection.insert(new BasicDBObject("_id", 1).append("tags", Util.list("mongo", "javascript")));

  // When
  DBObject result = collection.findOne(new BasicDBObject("tags", new BasicDBObject("$all", Arrays.asList())));

  // then
  assertNull(result);
}
```

**Comment by twillouer** [comment]
Hi,

thanks for the report.

It's difficult to maintain, because mongo change things between 2.6 and 3.X..

wich version for fongo and mongo do you use ?

**Comment by dario-campagna** [comment]
We are using MongoDB version 3.0.4, fongo version 2.0.1. We run the above test on the current fongo master branch, and on fongo v3 branch. It fails on both branches.

**Comment by twillouer** [comment]
Nice tought, corrected in "v3" branch !
