### ISSUE TITLE
Support $lt / $gt

### ISSUE THREAD

**Issue by FeNoMeNa** [fakemongo/fongo#130]
The fake implementation of Mongo 3.0 does not support $lt / $gt operators. I have run my tests on Fongo and real Mongo instance, but tests on Fongo have failed. For the test purposes i have used integer numbers.

Fongo version: 2.0.2
Java driver: 3.0.0

Thanks.

**Comment by twillouer** [comment]
```java

  @Test
  public void $lg_should_work() {
    // Given
    MongoCollection collection = newCollection();
    collection.insertOne(docId(1));
    collection.insertOne(docId(2).append("b", 5));
    collection.insertOne(docId(3).append("b", 5));
    collection.insertOne(docId(4));
    collection.insertOne(docId(5).append("b", 6));

    // When
    final FindIterable iterable = collection.find(Filters.gt("b", 5));

    // Then
    Assertions.assertThat(toList(iterable)).containsExactly(docId(5).append("b", 6));
  }

```

works, do you have an example ?

**Comment by FeNoMeNa** [comment]
I'm sorry, everything is correct. My mistake was that I have asserted on the order of the received list of objects. Probably the implementation uses some sort of hashing structure. Sorry again.
