### ISSUE TITLE
BulkWriteResult.isAcknowledged is always true

### ISSUE THREAD

**Issue by Tolsi** [fakemongo/fongo#134]
Even is I use unacknowledged WriteConcern, isAcknowledged on BulkWriteResult always return true
```
val res = bulk.execute(WriteConcern.Unacknowledged)
assert(res.isAcknowledged == false, "wtf?")
```
I use casbah 2.8.1 and mongo-java-driver 2.13.1

**Comment by twillouer** [comment]
Right, thanks for the report
