### ISSUE TITLE
Update with Upsert

### ISSUE THREAD

**Issue by stoked10** [fakemongo/fongo#136]
In 2.0.1 FongoConnection.update line 104 update is called with only two properties, the filter and the data to update, it ignores multi and upsert. The result is that for Mongo driver 3.0.2 it calls DBCollection.update on line 500. This call defaults to false for upsert and for multi. The behavior is such that if you call a collection.updateOne(query, update, updateOptions).upsert(true), the update will not be written if the query does not return a result. I believe the fix should be on line 104:

```
final WriteResult writeResult = collection.update(dbObject(update.getFilter()), dbObject(update.getUpdate()), update.isUpsert(), update.isMulti());
```

**Comment by twillouer** [comment]
Hi,

have you try against the 2.0.2 version of fongo ?

https://github.com/fakemongo/fongo/commit/91ba255e1d522971fada9c348d0edfb15d57008f

**Comment by stoked10** [comment]
That did the trick, thanks!
