### ISSUE TITLE
ReplaceOne with Upsert

### ISSUE THREAD

**Issue by stoked10** [fakemongo/fongo#137]
In 2.0.2 in FongoConnection.updateCommand an update of REPLACE ignores if it is an upsert or not. in Mongo 3 the only way to replace a record or create it if it doesn't exist is with replaceOne and upsert(true).

The code change should be:

```
switch (update.getType()) {
 case REPLACE:
  if (update.isUpsert()) {
   bulkWriteOperation.find(dbObject(update.getFilter())).upsert().replaceOne(dbObject(update.getUpdate()));
  } else {
   bulkWriteOperation.find(dbObject(update.getFilter())).replaceOne(dbObject(update.getUpdate()));
}

**Comment by twillouer** [comment]
closes by #140
