### ISSUE TITLE
Fongo 1.6.3: NoSuchMethodError exception thrown from FongoDB.renameCollection

### ISSUE THREAD

**Issue by mhottinger1** [fakemongo/fongo#138]
During `FongoDB.renameCollection` the method is checking for indexes to carry over from the source collection to the target collection. When such indexes are found, the `FongoDB.renameCollection` method calls `FongoDBCollection.createIndex`, but the input parameters don't match the `FongoDBCollection.createIndex` method signature.

`FongoDBCollection.createIndex(DBObject, String, boolean)` should be `FongoDBCollection.createIndex(DBObject, DBObject, DBEncoder)`

**Comment by twillouer** [comment]
Hi,

in wich version of fongo ?

**Comment by mhottinger1** [comment]
Hi @twillouer. Thanks for your reply. This is a problem in Fongo 1.6.3.

**Comment by twillouer** [comment]
Hi,

I try to understand your problem, but I can't.
In drivers 2.13, 

```java
    @Deprecated
    public abstract void createIndex(DBObject keys, DBObject options, DBEncoder encoder);
```

this method is deprecated.

Can you check 0e07352fa737610f571b32222149547f5501302c and provide me an example of your problem ?

**Comment by twillouer** [comment]
@mhottinger1 hello, any news ?
