### ISSUE TITLE
FongoDBCursor: getLimit() and getBatchSize() are not working correctly

### ISSUE THREAD

**Issue by rzanner** [fakemongo/fongo#142]
For DBCursor iterations the current instance is always copied using the method copy(). 
In this call the FindOptions attribute of the base class remains unset and therefore does not have the same settings as the current instance.

Unfortunately the methods getLimit() and getBatchSize() are just delegating to the base class and therefore return the initial values of the unset base class version, and *not* the correctly copied values of the new instance.

So, in order to make limit() working correctly, the method must be changed to 

    @Override
    public int getLimit() {
        // rzanner: do not delegate to the base class since this instance may be created by #copy()
        // and then does not have the correct state in super.findOptions!
        return this.findOptions.getLimit();
    }

The getBatchSize() method must be adapted similarly:

    @Override
    public int getBatchSize() {
        // rzanner: do not delegate to the base class since this instance may be created by #copy()
        // and then does not have the correct state in super.findOptions!
        return this.findOptions.getBatchSize();
    }

**Comment by twillouer** [comment]
Hi,

witch version of Fongo do you use ?

**Comment by twillouer** [comment]
forget my question, can you check again with v3 branch ?
