### ISSUE TITLE
Null handling is incorrect with $in operator

### ISSUE THREAD

**Issue by jimleroyer** [fakemongo/fongo#144]
Hello,

We've found a bug with the usage of the `$in` operator when we pass in a null value. Normally, passing a `null` to the `in` operator would indicate that absence of the field should be reported back by the query, as [documented here](http://docs.mongodb.org/manual/faq/developers/#faq-developers-query-for-nulls). Fongo disregards the null value though and does not behave the same as MongoDB on the null handling. The following test would fail in `ExpressionParserTest` with the latest code base:

```
@Test
public void testInOperatorWithNullValue() {
  // Querying for null should return positive if the field is absent.
  // See: http://docs.mongodb.org/manual/faq/developers/#faq-developers-query-for-nulls
  DBObject query = new BasicDBObjectBuilder().push("a").add("$in", asList(2, 3, null)).pop().get();
  List<DBObject> results = doFilter(
      query,
      new BasicDBObject("a", asList(1, 3)),
      new BasicDBObject("a", 1),
      new BasicDBObject("a", 3),
      // Include an element with no 'a' field: this should get returned.
      new BasicDBObject("b", 1)
  );
  assertEquals(Arrays.<DBObject>asList(
      new BasicDBObject("a", asList(1, 3)),
      new BasicDBObject("a", 3),
      new BasicDBObject("b", 1)
  ), results);
}
```

I will open a pull request with this test along with the one-liner fix that should make it pass. Feedback on it would greatly be appreciated as we forked the project for now to patch a past version we need to use. 

Thanks a lot for this library as this saves us lot of troubles for testing our MongoDB layers at Expedia!

**Comment by twillouer** [comment]
Thanks !
