### ISSUE TITLE
Allow to use non default host and port

### ISSUE THREAD

**Issue by r0main** [fakemongo/fongo#148]
In the Fongo class there is only one constructor :

    public Fongo(String name) {
        this.name = name;
        this.serverAddress = new ServerAddress(new InetSocketAddress(ServerAddress.defaultHost(), ServerAddress.defaultPort()));
        this.mongo = createMongo();
    }

Therefore it's not possible to change the host and port of Fongo. Could you add another constructor allowing client to easily instantiate a Fongo on a different host and port ? Something like :

    public Fongo(String name, ServerAddress serverAddress) {
        this.name = name;
        this.serverAddress = serverAddress;
        this.mongo = createMongo();
    }

As Fongo fields are "private final", I didn't found any solution to start Fongo/Mongo on different port. It can be a problem on CI servers where multiple build would start Fongo on the same port.

**Comment by twillouer** [comment]
Hi,

ServerAddress is totally fake, there is not a real port opened on the server.

Are you sure it's a problem for you ?

**Comment by r0main** [comment]
*Are you sure it's a problem for you ?*
 * No. I read the code and thought it would cause problem if I wanted to start multiple Fongo as I saw host and port in this class. I didn't realize Fongo is only in memory and doesn't open port at all.

Sorry for the mistake. Does this mean there is no way to access Fongo outside of the current JVM ?

**Comment by twillouer** [comment]
Yes, it's only for unit testing, local in the jvm :)

**Comment by r0main** [comment]
Ok we were trying to use it in integration test. Thank you for your time. You can close the "issue".
