### ISSUE TITLE
matchedCount discrepancy in AcknowledgedBulkWriteResult

### ISSUE THREAD

**Issue by ddossot** [fakemongo/fongo#149]
For an ordered `BulkWriteOperation` which contains only:

    bulkOperation.find(query).upsert().updateOne(dbObject);

where the query will not match and thus yield an insert.

With fongo 2.0.2, I get this result:

AcknowledgedBulkWriteResult{insertedCount=0, matchedCount=1, removedCount=0, modifiedCount=0, upserts=[BulkWriteUpsert{index=0, id=4}]}

With mongo 2.6.11, I get:

AcknowledgedBulkWriteResult{insertedCount=0, matchedCount=0, removedCount=0, modifiedCount=0, upserts=[BulkWriteUpsert{index=0, id=4}]}

Fongo increments `matchedCount` even if no document was matched.

**Comment by twillouer** [comment]
Hi,

yes, I think this is dependant of the mongo version. Do you have try with Mongo 3.X ?
I will try asap.

**Comment by ddossot** [comment]
I observe the same behaviour with Mongo 3.0.7.

**Comment by twillouer** [comment]
Thanks !
Let me kown if you need a version

**Comment by ddossot** [comment]
Let me first test a snapshot and if all good, a version will be great :+1:

**Comment by twillouer** [comment]
ok, on v3 branch !

**Comment by ddossot** [comment]
Super happy to confirm `2.0.3-SNAPSHOT` works great :bow:

Release time? :smile:

**Comment by twillouer** [comment]
12 hours + synchronisation with maven central :-)

**Comment by twillouer** [comment]
done :)
