### ISSUE TITLE
FongoMapReduceOutput leads to NullPointerException when accessing statistics

### ISSUE THREAD

**Issue by ddossot** [fakemongo/fongo#153]
The following constructor:
```java
  public FongoMapReduceOutput(DBObject command, final DBCollection collection) {
    super(command, collection.find(), null, collection);
  }
```
passes `null` instead of an instance of `MapReduceStatistics` to the super constructor.

This leads to NPEs when calling `com.mongodb.MapReduceOutput.getDuration()`.

**Comment by twillouer** [comment]
In fongo 2.0.3 ? (you can test against the v3 branch)

**Comment by ddossot** [comment]
Sorry, yes, this is with `2.0.3`. Unfortunately I can't test anymore because my m/r scripts fail due to #154, sorry :crying_cat_face:

**Comment by twillouer** [comment]
Can you check again ?
