### ISSUE TITLE
$push.$each does not accept varags

### ISSUE THREAD

**Issue by dtracers** [fakemongo/fongo#156]
It appears in fongo that you can only use a BasicDBLists when using the push operator.

When using the mongo library (2.12.3 in maven) it accepts varags

example code:
```
public void method(long... values) {
    db.insert(new BasicDbOject(key, values));
}
```

in mongo the above works and creates actual values in the mongo database.

in fongo you get
```
Caused by: com.github.fakemongo.FongoException: $push.$each value expected to be of type com.mongodb.BasicDBList but is class [J toString:[J@7adda9cc
```

Note I did not try this with other types of lists so it could be that those would fail too

**Comment by twillouer** [comment]
Hi,
can you check against the master branch to see if all is fine ?
