### ISSUE TITLE
Allow adjustment of Mongo version

### ISSUE THREAD

**Issue by BenRomberg** [fakemongo/fongo#159]
After having had some problems with different Mongo versions on our production machines, we've implemented a version check in our code ensuring a minimum Mongo version is being spoken to.

This check fails with Fongo (2.0.3), as Fongo is always returning "2.4.5" as its version when using the command "buildInfo" (see https://github.com/fakemongo/fongo/blob/master/src/main/java/com/mongodb/FongoDB.java#L226). It would be nice if this version was not hardcoded and could be altered when initializing Fongo, so our version check wouldn't fail in our tests. Actually, it seems that the version is already configured when calling the Fongo constructor, so all there is left to do would be to replace the "2.4.5" with something like `fongo.getServerVersion()` and build the String from it.

I'd be happy to submit a pull request if someone could confirm it would be merged.

An alternative would be a way to access the ServerVersion from outside Mongo, but so far I haven't been successful.

By the way: Happy Fongo user since around 1.5 years, keep up the great work! :-)

**Comment by twillouer** [comment]
Hi,

it was initially the plan to set the ServerVersion. You can submit a PR if you want :)

**Comment by BenRomberg** [comment]
Great, submitted #162.
