### ISSUE TITLE
Aggregation on date returns null

### ISSUE THREAD

**Issue by riyyaz** [fakemongo/fongo#163]
Fongo fongo = new Fongo("mongo server 1");

		DB db = fongo.getDB("mydb");
		DBCollection collection = db.getCollection("mycollection");
		collection.insert(new BasicDBObject("t", new java.util.Date()));

		BasicDBObject obj = new BasicDBObject("$group",
				new BasicDBObject("_id", new BasicDBObject("day", new BasicDBObject("$dayOfMonth", "$t"))));

		AggregationOutput ao = collection.aggregate(Arrays.asList(obj));
		Iterator<DBObject> dbo = ao.results().iterator();
		while (dbo.hasNext()) {
			System.out.println(dbo.next());
		}

The above code returns the aggregated day as null

{ "_id" : { "day" :  null }}

**Comment by twillouer** [comment]
Hi, can you check against the v3 branch  ?
