### ISSUE TITLE
Fongo upsert for non-existing document seems to write the document incorrectly

### ISSUE THREAD

**Issue by tukaaa** [fakemongo/fongo#164]
See also: http://stackoverflow.com/questions/33869208/fongo-upsert-for-non-existing-document-seems-to-write-the-document-incorrectly
I'm trying to upsert a document in Fongo, but I get different results when using Fongo itself or Mongo. My documents are identified by a set of two fields (let's say a compound key), so in the Java code I do the following: 

    @Override
    public boolean insertOrUpdate(SomeMessage message) throws SQLException {
        collection.updateOne(
            message.getIdQuery(),
            new Document()
                .append("$set", new Document()
                    .append(message.getSubtype().name(),
                            message.asMongoDocument())
                    .append(FIELD_LAST_UPDATED, new Date())
                ),
            new UpdateOptions().upsert(true)
        );
        return true;
    }

where collection is a `MongoCollection` object and the `getIdQuery()` method produces the following document: 

    public Document getIdQuery() {
        return new Document()
            .append("$and", Arrays.asList(new Document[]{
                new Document().append("id1", getId1()),
                new Document().append("id2", getId2())
            }));
    }

When writing to real Mongo (`FongoRule(true)`), I get the expected document from Mongo: 

    {
      "_id":{
        "$oid":"5652e2668f02dbf09c03ed0a"
      },
      "id1":234,
      "id2":123,
      "subdocument":{...},
      "lastUpdated":{
        "$date":1448272664564
      }
    }

but from Fongo itself (`FongoRule()`) I seem to get a completely different one: 

    {
      "_id":{
        "$oid":"5652e4d83727549eb6833bf3"
      },
      "$and":[
        {
          "id1":123
        },
        {
          "id2":234
        }
      ],
      "subdocument":{...},
      "lastUpdated":{
        "$date":1448273112379
      }
    }

My expectation is that, given that the document does NOT exist, the Db created a new document with the compound it and insert the sub-document. Mongo does it, fongo doesn't. Seems a bug to me, but maybe I'm doing the AND query the wrong way and somehow Mongo is smart enough to understand what I really wanted? 

I'm using Fongo version 2.0.3 and Mongo driver version 3.0.4 (3.1.1 doesn't seem to work with Fongo) with a local installation of Mongo 3.0.7.

**Comment by twillouer** [comment]
Hi, can you check against the v3 branch ?
