### ISSUE TITLE
ClassCastException: Fongo assumes WriteConcern.w is an integer

### ISSUE THREAD

**Issue by mrmanc** [fakemongo/fongo#171]
I’ve encountered a scenario which causes a ClassCastException when storing a document in Fongo. To trigger this scenario you need to specify a non numeric WriteConcern (e.g. WriteConcern.MAJORITY) and store a couple of documents with the same identifier.

Looks like the error was in [FongoDBCollection.java in fongo-2.0.3](https://github.com/fakemongo/fongo/blob/ef8ba04ae852f8fc84c94f9c0bcced7680f1a510/src/main/java/com/mongodb/FongoDBCollection.java#L126), but it appears to be smarter in the HEAD, no longer assuming that it is safe to call getW().

I tried to find a version I could build locally to benefit from the fix but everything I tried broke other tests. Should I sit tight and wait for the next release or is there something I could do to help? I’ve included a test case below.

Thanks, Mark

```java
import com.github.fakemongo.Fongo;
import com.mongodb.WriteConcern;
import org.jongo.Jongo;
import org.jongo.MongoCollection;
import org.junit.Test;

public class FongoCastTest {
    
    @Test
    public void checkFongoSupportsMajority() {
        Jongo jongo = new Jongo(new Fongo("fake-mongo-server").getDB("fake-database"));
        MongoCollection turnips = jongo.getCollection("turnip").withWriteConcern(WriteConcern.MAJORITY);
        turnips.insert(new Turnip("turnip"));
        turnips.insert(new Turnip("turnip"));
    }

    private class Turnip {
        private String _id;

        public Turnip() {
        }

        public Turnip(String _id) {
            this._id = _id;
        }
    }
}

```

**Comment by twillouer** [comment]
Right, I think this issue is resolved in the v3 branch, can you check ?
Le 17 déc. 2015 18:47, "Mark Crossfield" <notifications@github.com> a
écrit :

**Comment by mrmanc** [comment]
That's great news. Will check tomorrow. 👍🏻

**Comment by mrmanc** [comment]
Thanks @twillouer… that has fixed our tests. Whoop! :smile: 

Would you like the test I mentioned (with the expected exception specified) added as a PR? Or are you happy with your existing coverage?

**Comment by twillouer** [comment]
all PR are welcome !
