### ISSUE TITLE
Throw exception when dropping unknown index

### ISSUE THREAD

**Issue by BenRomberg** [fakemongo/fongo#176]
In MongoDB, when trying to drop an index that doesn't exist, the Java Driver throws an exception:
```
Caused by: com.mongodb.MongoCommandException: Command failed with error -1: 'index not found with name [nonExistingIndex_1]' on server localhost:27017. The full response is { "nIndexesWas" : 2, "ok" : 0.0, "errmsg" : "index not found with name [nonExistingIndex_1]" }
```

It would be nice if Fongo could mirror this behavior, as it would force my migration tests to drop an actually existing index rather than dropping an arbitrary index. Currently, Fongo silently ignores dropping an unknown index without throwing anything.

I'm willing to submit a pull-request if this is deemed feasible.

**Comment by twillouer** [comment]
Sorry for the late.

Yes, PR are always welcome :)

**Comment by twillouer** [comment]
Hi,

can you check against master or v3 ?

**Comment by BenRomberg** [comment]
@twillouer: Sorry for the late reply. Works like a charm with 2.0.6, TYVM!
