### ISSUE TITLE
[$or] operator expected to be of type java.util.Collection

### ISSUE THREAD

**Issue by robgraeber** [fakemongo/fongo#177]
Hey guys I'm getting the following error:
```
failed: com.github.fakemongo.FongoException: [$or] operator expected to be of type java.util.Collection but is class scala.collection.immutable.$colon$colon toString:List({ "startDate" : { "$exists" : false}}, { "startDate" : { "$lt" : { "$date" : "2016-01-04T23:48:46.457Z"}}})
```

When running the following query:
```
val now = new Date()
$and("published" $ne false,
   $or( "startDate" $exists false, "startDate" $lt now ),
   $or( "expiration" $exists false, "expiration" $gt now )
)
```

Is there any workaround for this or tips to debug it?

**Comment by robgraeber** [comment]
This is with fongo v1.5.5 and using Scala/Casbah, seems like Casbah's DSL operators ($and/$or) gets converted into scala $colon$colon lists instead of DBObjectList. It works if I manually build the DBObject.

**Comment by twillouer** [comment]
Hi,

can you try against fongo v1.6.5 before I check ?

Thanks

**Comment by robgraeber** [comment]
Hey @twillouer, I confirm it still happens in 1.6.5.

**Comment by twillouer** [comment]
Hi,

can you try against the master branch plz ?
