### ISSUE TITLE
$group in aggregate query doesn't work if there're more than one field in the query

### ISSUE THREAD

**Issue by jfcorugedo** [fakemongo/fongo#178]
First of all, thanks to this project. It's quite useful and works pretty well. Keep up the good work!

Now, let me explain the problem. Given this content in my collection:

    { "_id" : "1", "test" : 1.0, "City" : "Madrid", "groupType" : "control"},
    { "_id" : "2", "test" : 10.0, "City" : "Madrid", "groupType" : "treatment"},
    { "_id" : "3", "test" : 2.0, "City" : "Madrid", "groupType" : "control"},
    { "_id" : "4", "test" : 20.0, "City" : "Madrid", "groupType" : "treatment"},
    { "_id" : "5", "test" : 3.0, "City" : "London", "groupType" : "control"},
    { "_id" : "6", "test" : 30.0, "City" : "London", "groupType" : "treatment"},
    { "_id" : "7", "test" : 4.0, "City" : "Paris", "groupType" : "control"},
    { "_id" : "8", "test" : 40.0, "City" : "Paris", "groupType" : "treatment"},
    { "_id" : "9", "test" : 5.0, "City" : "Paris", "groupType" : "control"},
    { "_id" : "10", "test" : 50.0, "City" : "Paris", "groupType" : "treatment"}

I want to know the average of the variable **'test'** grouping by **'City'** and **'groupType'**.

In order to do that, I'm executing the following query:

    { 
      "$group" : { 
          "_id" : { "groupType" : "$groupType" , "City" : "$City"} , 
          "average" : { "$avg" : "$test"}
      }
    }

I expect a result document like this:

    { 
      "_id" : {
         "groupType" : "treatment" , 
         "City" : "Madrid"
      } , 
      "average" : 15.0
    } , 
    { 
       "_id" : { 
          "groupType" : "control" , 
          "City" : "Madrid"
       } , 
       "average" : 1.5
    }
    ...

Executing this query with a real mongo, I can get the expected data, but executing the same case with Fongo I can't obtain the **average** value.

If I remove one of the variables from the **$group** operator, then I receive a correct value in average property.

Is it a bug? Am I doing something wrong? Does fongo support this aggregate query?

Thanks in advance
​

**Comment by twillouer** [comment]
Hi,

witch version of fongo ?
I think you're right and the $avg function is not in fongo

**Comment by twillouer** [comment]
Hi,

I take all of your data, and with real mongo:
```
[{"_id":{"groupType":"treatment", "City":"Paris"}, "average":45.0}, {"_id":{"groupType":"treatment", "City":"London"}, "average":30.0}, {"_id":{"groupType":"control", "City":"London"}, "average":3.0}, {"_id":{"groupType":"control", "City":"Paris"}, "average":4.5}, {"_id":{"groupType":"treatment", "City":"Madrid"}, "average":15.0}, {"_id":{"groupType":"control", "City":"Madrid"}, "average":1.5}]
```

with fongo:
```
[{"_id"={"groupType"="treatment", "City"="Madrid"}, "average"=15.0}, {"_id"={"groupType"="treatment", "City"="Paris"}, "average"=45.0}, {"_id"={"groupType"="control", "City"="Madrid"}, "average"=1.5}, {"_id"={"groupType"="treatment", "City"="London"}, "average"=30.0}, {"_id"={"groupType"="control", "City"="London"}, "average"=3.0}, {"_id"={"groupType"="control", "City"="Paris"}, "average"=4.5}]
```

only a difference in order.

**Comment by jfcorugedo** [comment]
Hi!

We're using fongo 1.5.10, and using that version we can't obtain right results. It returns all the expected documents, but the **average** property is empty in all of them.

Which version did you use in your test?

I can test that version in our environment and tell you the results.

Thanks in advance!

**Comment by twillouer** [comment]
hum.. why not trying the latest version of fongo ?
1.6.6 latest release, 1.6.7-SNAPSHOT if you can compile the master branch

**Comment by jfcorugedo** [comment]
Well, the problem is that we're currently using nosqlunit module, and fongo is imported through this dependency.

nosqlunit-mongodb 0.8.1 depends on fongo 1.5.10.

I can replace this version of fongo importing a new one in the root of my pom, but I have to check if nosqlunit can deal with that version of fongo.

On the other hand, I can't use your snapshot version, because my code is already in production and I can only use stable release, so I'll try with 1.6.6.

I'm going to test this scenario and I'll let you know what the result is.

Thanks

**Comment by jfcorugedo** [comment]
Ok, it works.

However when I update my dependency from 1.5.10 to 1.6.6 some tests have failed due to these versions have a different behaviour.

If the test performs a query over an nonexistent collection, fongo 1.5.10 creates that new collection although no documents have been inserted, but fongo 1.6.6 doesn't create that collection unless at least a single document is inserted.

Anyway it's good, my code now works and I reckon the behaviour of 1.6.6 is better than the behaviour of 1.5.10.

Thanks a lot!
