### ISSUE TITLE
Projection on aggregation does not work with $size

### ISSUE THREAD

**Issue by zxkane** [fakemongo/fongo#182]
Fongo: 1.6.5

Below query can be executed in mongo shell, then return a field named **likedCount** with the size of array field `liked`.

```javascript
db.myCol.aggregate([{$match: {liked: {$ne: null}}}, {$project: {viewCount: 1, likedCount: {$size: ["$liked"]}, liked: 1} }, {$sort: {viewCount: -1, likedCount: -1}}, {$limit: 1}])
```

**Comment by twillouer** [comment]
Hi,

can you check against master plz ?

**Comment by zxkane** [comment]
@twillouer , thanks for your fix. It works fine when using master SNAPSHOT.

BTW, I have to explicitly specify the version of mongodb driver as `2.14.1`. Otherwise the `AbstractMethodError` would be thrown if using the driver `2.13.3` that was taken by spring data mongodb 1.8.2.

**Comment by twillouer** [comment]
Right, will fix that soon.

**Comment by twillouer** [comment]
done, compatibility with 2.13.

But, difficult to maintain

**Comment by KrisGerhard** [comment]
I'm using mongo driver 3.4 and the problem seems to be back.

`java.lang.String cannot be cast to com.mongodb.BasicDBList`
