### ISSUE TITLE
BulkWrite upsert not returning correct BulkWriteResult

### ISSUE THREAD

**Issue by worrel** [fakemongo/fongo#186]
I'm using Fongo 2.0.5 and the 3.2.1 Mongo java drivers.

bulkWrite with UpdateOneModel and UpdateOptions.upsert(true) is not returning any information in the BulkWriteResult when it does in fact perform an upsert.  This appears to be because the upserted DbObject doesn't have "_id" (see [FongoDBCollection#L307](https://github.com/fakemongo/fongo/blob/fongo-2.0.5/src/main/java/com/mongodb/FongoDBCollection.java#L307) and [FongoDBCollection#L1174](https://github.com/fakemongo/fongo/blob/fongo-2.0.5/src/main/java/com/mongodb/FongoDBCollection.java#L1174)

I have Scala code that inspects the BulkWriteResults & needs to retrieve the IDs of the upserts for further processing.  The code works correctly against live MongoDB 3.2 and 3.0 but my unit tests of the code fail.

I'll try construct a minimal failing example, because adding an UpdateOneModel to the Fongo unit test actually succeeds.

**Comment by worrel** [comment]
I think I've got it - the upsert fails to return upsertedId for UpdateOneModel if the query doesn't contain "_id".

The reason is the upsertedId is being extracted from the query object, rather than the update object that is upserted - this seems incorrect to me.

**Comment by twillouer** [comment]
ping me if you need a release
