### ISSUE TITLE
Aggregation $out keyword is broken in Fongo - Not copying data to another collection

### ISSUE THREAD

**Issue by codethala** [fakemongo/fongo#193]
```
import com.mongodb.client.MongoDatabase;
import org.mongodb.morphia.Datastore;
     .
     .
     .
MongoDatabase mongoDatabase;
Datastore sourceDatastore;
Datastore destinationDatastore;
     .
     .
     .
mongoDatabase.getCollection(sourceDatastore.getCollection(Employee.class).getName())
         .aggregate(asList(project(include(Employee.FIELDS.toArray(EMPTY_STRING_ARRAY))),
              out(destinationDatastore.getCollection(Employee.class).getName())))
         .first();

```
**project** to **out** doesn't copy data from Source collection to Destination collection. No error or exception!!!

**$out** is not working on Fongo. 

Any help would be appreciated.

**Comment by twillouer** [comment]
Hi,

witch version of fongo ?

**Comment by ddossot** [comment]
This happens with fongo `2.0.5` and mongo java driver `3.2.2`.

**Comment by twillouer** [comment]
can you check against the v3 branch plz ?

**Comment by ddossot** [comment]
It works great, thank you :+1:

**Comment by ddossot** [comment]
And now, for the crucial question: any hope to get a release soon? If not, maybe a snapshot  :sweat_smile: ?

**Comment by twillouer** [comment]
tommorow morning in maven central :)
or now if you're lucky

**Comment by ddossot** [comment]
:dancers:
