### ISSUE TITLE
fongo 1.6.6 incompatible with mongo-java-driver changes introduced between 2.13.2 and 2.14.1

### ISSUE THREAD

**Issue by g1l3sp** [fakemongo/fongo#195]
I attempted to upgrade to the latest Mongo 2.x driver, 2.14.1, to obtain a bug fix, and found that a number of our tests are now failing due to unimplemented methods in FongoDBCollection.java.  The stack trace I got looks like:

    java.lang.AbstractMethodError: com.mongodb.DBCollection.executeBulkWriteOperation(ZLjava/lang/Boolean;Ljava/util/List;Lcom/mongdb/WriteConcern;Lcom/mongodb/DBEncoder;)Lcom/mongodb/BulkWriteResult;
	at com.mongodb.DBCollection.executeBulkWriteOperation(DBCollection.java:1904)
	at com.mongodb.DBCollection.executeBulkWriteOperation(DBCollection.java:1899)
	at com.mongodb.BulkWriteOperation.execute(BulkWriteOperation.java:116)

To temporarily work around the issue, I'm doing a classpath override (in other words dumping modified Fongo source into our project) of FongoDBCollection.java with these additional methods added in:

    @Override
    BulkWriteResult executeBulkWriteOperation(boolean ordered, Boolean bypassDocumentValidation, List<WriteRequest> requests, WriteConcern writeConcern, DBEncoder encoder) {
        // Ignore document validation parameter
        return executeBulkWriteOperation(ordered, requests, writeConcern, encoder);
    }

    @Override
    protected WriteResult insertImpl(List<DBObject> list, WriteConcern concern, DBEncoder encoder, Boolean bypassDocumentValidation) {
        // Ignore document validation parameter
        return insert(list, concern, encoder);
    }

    @Override
    protected WriteResult updateImpl(DBObject q, DBObject o, boolean upsert, boolean multi, WriteConcern concern, Boolean bypassDocumentValidation, DBEncoder encoder) {
        // Ignore document validation parameter
        return update(q, o, upsert, multi, concern);
    }

    @Override
    protected DBObject findAndModifyImpl(DBObject query, DBObject fields, DBObject sort, boolean remove, DBObject update, boolean returnNew, boolean upsert, Boolean bypassDocumentValidation, long maxTime, TimeUnit maxTimeUnit, WriteConcern writeConcern) {
        // Ignore document validation parameter
        return findAndModify(query, fields, sort, remove, update, returnNew, upsert, maxTime, maxTimeUnit, writeConcern);
    }

This clearly isn't a proper fix, but good enough for us since we're not using document validation in our project.  We are looking to upgrade to the Mongo 3.x driver in the not too distant future, but I imagine others stuck on 2.x for the time being will encounter this issue too, so I'm reporting it.

Thanks for the great project, it's been really useful for us!

**Comment by twillouer** [comment]
Hi,

can you try against the master branch ?
