### ISSUE TITLE
Async driver support

### ISSUE THREAD

**Issue by lujop** [fakemongo/fongo#198]
It's possible to use the 3.0 async driver with fongo?

**Comment by twillouer** [comment]
Hi,

now is it not possible, but I will check if the effort is hard or not

**Comment by CodeTripper** [comment]
+1 for async!

**Comment by marekzebrowski** [comment]
+1

**Comment by rusho** [comment]
+1

**Comment by twillouer** [comment]
in progress :)

**Comment by twillouer** [comment]
you can see the 'async' branch (not enought test for now, it's still a WIP version :))

**Comment by Krever** [comment]
Hello, any news on this?

**Comment by twillouer** [comment]
if you want to test, the async branch can be checked

**Comment by tfij** [comment]
is there any estimation of release date?

**Comment by twillouer** [comment]
only if someone can test before

**Comment by marekzebrowski** [comment]
we async version - https://github.com/sgrouples/fongo and it works for us

**Comment by pigne** [comment]
So it looks like the async branch has been merge to master. I have successuffly been using the async driver. Any plain on releasing it on the Central Repository?

**Comment by twillouer** [comment]
@pigne it's done (few hours if it's slowly)
