### ISSUE TITLE
Aggregate query needs to support $lookup

### ISSUE THREAD

**Issue by krraghavan** [fakemongo/fongo#203]
With Mongo 3.2 a new aggregation pipeline stage was introduced that allows a join between two collections (1-many).  Fongo needs to support that so that aggregation queries using this pipeline stage can be unit tested.

**Comment by krraghavan** [comment]
I have implemented this but since this would be my first submission here I'm not sure how to contribute this patch.  Would like some pointers to instructions so I can do this correctly and open a Pull request.

**Comment by twillouer** [comment]
Hi,

there is no "guideline", feel free to contribute (check format of files are same, at least :))

**Comment by krraghavan** [comment]
I'm guessing I need permissions to push.  I'm ready to do that but not sure how to get those permissions and generate a pull request.

**Comment by twillouer** [comment]
You need to fork the project in you own user.

You make the UT, the code, verify UT are ok, commit, push on your repository and then ask for a Pull Request

**Comment by krraghavan** [comment]
Got it
Thx
Raghavan

On Sun, Apr 24, 2016 at 10:33 AM, William Delanoue <notifications@github.com

**Comment by krraghavan** [comment]
Merged into main with PR #208
