### ISSUE TITLE
The $year operator requires a field name

### ISSUE THREAD

**Issue by lidonis** [fakemongo/fongo#205]
I have an error when i try to extract the year from a date.

**The full response is { "ok" : 0.0, "err" : "the $year operator requires a field name", "code" : 16020 }**

The aggregation looks like :

```
db.sales.aggregate(
   [
     {
       $project:
         {
           year: { $year: ["$date"] }
         }
     }
   ]
)
```

The same query works in mongo shell.

**Comment by twillouer** [comment]
Right, thanks.

you can check againts the v3 branch (or master as you prefer)

**Comment by lidonis** [comment]
It works with the v3 branch.

Thanks for fixing the issue so fast.
