### ISSUE TITLE
Support for insert, update and delete commands

### ISSUE THREAD

**Issue by coreyjv** [fakemongo/fongo#210]
I have a scenario where I need to use the `DB.command()` and `MongoDatabase.runCommand()`methods to execute [insert](https://docs.mongodb.com/manual/reference/command/insert/#dbcmd.insert), [update](https://docs.mongodb.com/manual/reference/command/update/#dbcmd.update) and [delete](https://docs.mongodb.com/manual/reference/command/delete/#dbcmd.delete) commands.

I would be willing to submit a PR for these if contributions are accepted.

**Comment by twillouer** [comment]
contributions are always welcome :)

**Comment by coreyjv** [comment]
@twillouer Fantastic! Do you mind if I submit PRs for each command separately to allow for smaller changes to be introduced that can be more easily reviewed?

**Comment by twillouer** [comment]
perfect :)

**Comment by coreyjv** [comment]
@twillouer,

I still have a couple more PRs to submit for update and delete. Should I open a new issue for reference or reference this closed one?

**Comment by twillouer** [comment]
@coreyjv yes please !
