### ISSUE TITLE
Different behavior compared to MongoDB using indexes on optional fields

### ISSUE THREAD

**Issue by bsautel** [fakemongo/fongo#211]
Hi all.

First of all, thanks for this wonderful tool. I would dream that every database have a fake in-memory database implementation such as Fongo!

I noticed that Fongo has a different behavior when using indexes regarding optional fields. The `{$exists: false}` query does not work when the field is indexed.

Here is a test case that reveals this issue:
```java
import com.github.fakemongo.Fongo;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import org.bson.Document;
import org.junit.Before;
import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class FongoTest {
    private MongoCollection<Document> testCollection;

    @Before
    public void setUp() {
        Fongo testDb = new Fongo("test");
        MongoDatabase test = testDb.getDatabase("test");
        testCollection = test.getCollection("test");
        testCollection.insertOne(new Document("_id", "id1").append("optionalField", "value"));
        testCollection.insertOne(new Document("_id", "id2"));
    }

    @Test
    public void shouldFindOneDocumentWithoutTheOptionalFieldWithNoIndex() {
        long result = countDocumentsWithoutOptionalField();

        // Success
        assertThat(result).isEqualTo(1);
    }

    @Test
    public void shouldFindOneDocumentWithoutTheOptionalFieldWithIndex() {
        testCollection.createIndex(new Document("optionalField", 1));

        long result = countDocumentsWithoutOptionalField();

        // Broken: result is 0
        assertThat(result).isEqualTo(1);
    }

    private long countDocumentsWithoutOptionalField() {
        return testCollection.count(new Document("optionalField", new Document("$exists", false)));
    }
}
```
I'a using Fongo 2.0.7.

This query works in the real MongoDB engine (at least in version 2.6).

Note that it sounds like in MongoDB using `{optionalField: null}` also matches documents which don't have the `optionalField` field and it does not work either in Fongo.

Thanks!

**Comment by twillouer** [comment]
Hi,

can you test against the master branch ?

**Comment by bsautel** [comment]
Hi @twillouer , I confirm this change fixes the issue. Thanks!

Note that there is still the difference with the real MongoDB engine regarding `null` and `{$exists: false}`, I open a new issue for that.
