### ISSUE TITLE
NPE when getting the replica status of a Fongo instance

### ISSUE THREAD

**Issue by milanov** [fakemongo/fongo#215]
I'm using Fongo as a database during tests. The setup is the following:

``` java
@Bean
public Mongo mongo() { return new Fongo("test").getMongo(); }
```

From there on the Mongo instance is used in several integration tests, but one of the dependencies I'm using is calling `Mongo#getReplicaSetStatus`. That method in turn calls `getClusterDescription()`, which fails with a NPE, because the `cluster` is not initialised.

I saw that in Fongo's `MockMongoClient` there is commented-out code that seems to provide this cluster object. Are there plans to uncomment it or to provide the option to customise it in some way. That would be greatly appreciated.

**Comment by milanov** [comment]
Hello again. Since this issue is blocking our daily work, could you give some tips on fixing it so that I try to submit a fix by opening a PR? Any hints or directions would be greatly appreciated.

**Comment by moisko** [comment]
Hi, any plans when this issue will be resolved?

**Comment by twillouer** [comment]
no, sorry, I don't have a solution for now

**Comment by twillouer** [comment]
Hi,

can you try against the master branch ?

**Comment by moisko** [comment]
Will version 2.0.11 include this fix?

**Comment by twillouer** [comment]
Yes

Envoyé avec AquaMail pour Android
http://www.aqua-mail.com

**Comment by moisko** [comment]
any plans when it will be released?

**Comment by twillouer** [comment]
Done :-)

Envoyé avec AquaMail pour Android
http://www.aqua-mail.com

**Comment by moisko** [comment]
Merci pour cette release! Ca marche parfaitement.

**Comment by moisko** [comment]
Bonjour twillouer,
Ce commit https://github.com/fakemongo/fongo/issues/260 en fait est un fix
qui nous est necessaire pour nos tests d'integration. Est-il possible que
la version 2.0.11 contient ce fix est plus precisement quand vous allez
faire release?

Cordialement, Boris
