### ISSUE TITLE
getCollection() doesn't register a new collection as it does in com.mongodb.DB

### ISSUE THREAD

**Issue by tereigo** [fakemongo/fongo#221]
If you do:
 val client = new Fongo(testName)
 val mongoDb = client.getDB(testName + "_db")
 val collection = mongoDb.getCollection(testCollectionName)

The it doesn't register a new collection and thus 
 mongoDb.collectionNames() returns an empty Set

**Comment by twillouer** [comment]
Hi,

There is already a test for this:
```
  @Test
  public void testGetCollection() {
    DB db = fongoRule.getDB();
    DBCollection collection = db.getCollection("coll");
    assertNotNull(collection);
    assertSame("getCollection should be idempotent", collection, db.getCollection("coll"));
    assertSame("getCollection should be idempotent", collection, db.getCollectionFromString("coll"));
    assertEquals(newHashSet(), db.getCollectionNames());
    **collection.insert(new BasicDBObject("_id", 1));**
    assertEquals(newHashSet("coll", "system.indexes"), db.getCollectionNames());
  }
```

does MongoDB change the behavior ?
witch version of MongoDB do you use ?

**Comment by tereigo** [comment]
I'm using Casbah driver for Scala
Fongo: 2.0.6
Casbah version: 3.1.1
Java driver: 3.2.2

Real Mongo version: 3.2.8 - I'm comparing against

**Comment by tereigo** [comment]
Here are the use-cases I tried:
This one works fine:
  test("Fongo createCollection + getCollection + getCollectionNames") {
    val fongo = new Fongo("in-memory MongoDB")
    val db = fongo.getDB("test")
    val createCollection = db.createCollection("coll", new BasicDBObject())
    val getCollection = db.getCollection("coll")
    createCollection shouldBe getCollection
    val collectionNames = db.getCollectionNames
    collectionNames.size() shouldBe 2
  }

This one fails because  db.getCollection("coll") doesn't register this collection in FongoDB.collMap via addCollection():
  test("Fongo getCollection + getCollectionNames") {
    val fongo = new Fongo("in-memory MongoDB")
    val db = fongo.getDB("test")
    val getCollection = db.getCollection("coll")
    val collectionNames = db.getCollectionNames
    collectionNames.size() shouldBe 2
  }

In real Casbah driver if you call getCollection("test_coll") then it's returned in the next db.getCollectionNames() call

**Comment by tereigo** [comment]
It works fine now with 2.0.10-SNAPSHOT version

**Comment by stuartgreenlees** [comment]
I am having the same problem. Any idea when the 2.0.10 version will be released?

**Comment by tereigo** [comment]
Yes, I've been waiting for the next 2.10 release for 2 months already as well to start using as a substitute it for our Mongo 3.2.8 version.

**Comment by twillouer** [comment]
Hi,
close the issue if the new release of 2.0.10 is fine for you
