### ISSUE TITLE
db.collectionNames() includes "system.indexes" into the collections list

### ISSUE THREAD

**Issue by tereigo** [fakemongo/fongo#222]
After there statements:
    val client = new Fongo(testName)
    val mongoDb = client.getDB(testName + "_db")
    val collection = mongoDb.createCollection(testCollectionName, new BasicDBObject())

db.getCollectionNames() returns a Set of (testCollectionName, "system.indexes")
whereas Casbah driver working against the real Mongo instance returns just Set of (testCollectionName)

Fongo 2.0.6
MongoDB: 3.2.8
Scala Casbah driver: 3.1.1
Java driver: 3.2.2

**Comment by twillouer** [comment]
Hi,

same things here

```

  @Test
  public void should_createCollection_create_the_collection() {
    DB db = fongoRule.getDB("db");
    db.createCollection("coll", new BasicDBObject());
    **assertEquals(Sets.newHashSet("coll", "system.indexes"), db.getCollectionNames());**
  }
```

I will check if MongoDB change this.

**Comment by tereigo** [comment]
I'm using Casbah driver for Scala
Fongo: 2.0.6
Casbah version: 3.1.1
Java driver: 3.2.2

Real Mongo version: 3.2.8 - I'm comparing against

**Comment by twillouer** [comment]
Hi,

can you test against the master branch ?

**Comment by tereigo** [comment]
It works fine now with 2.0.10-SNAPSHOT version
