### ISSUE TITLE
Fongo.getDB(String) should return com.mongodb.DB but returning com.mongodb.FongoDB

### ISSUE THREAD

**Issue by manojVivek** [fakemongo/fongo#233]
Getting the following error while calling getDB method using fongo 1.6.7:

`java.lang.NoSuchMethodError: com.github.fakemongo.Fongo.getDB(Ljava/lang/String;)Lcom/mongodb/DB;`

The signature of Fongo.getDB(String) in 1.6.7 is 
` public FongoDB getDB(String dbname)`
which should be
` public DB getDB(String dbname)`

The versions before this(<1.6.7) has correct signature.

**Comment by twillouer** [comment]
Hi,

can you provide a test class ?
because FongoDB extends from DB and I'm not sure to understand where this can be a problem ?

**Comment by manojVivek** [comment]
Sorry for the inconvenience. This is not an issue. I had the class compiled with a different Fongo version and executed with a different version.
