### ISSUE TITLE
Add support for $filter directive in $project

### ISSUE THREAD

**Issue by lukasz-baran** [fakemongo/fongo#236]
Starting from Mongodb v3.2 projections may contain `$filter` element for filtering arrays. It is of course a part of Aggregation Framework: https://docs.mongodb.com/v3.2/reference/operator/aggregation/filter/

Unfortunately there is no support for this feature in Fongo. Perhaps it is because Fongo is not up-to-date with Mongo 3.x features.

Here is the sample taken from the URL above - as you can see `$filter`s can have sophisticated syntax. Especially `cond` block can have its own grammar. And there can  be references to existing values (in the example below they start with double $ character). 

> {
>   $filter: {
>      input: [ 1, "a", 2, null, 3.1, NumberLong(4), "5" ],
>      as: "num",
>      cond: { $and: [
>         { $gte: [ "$$num", NumberLong("-9223372036854775807") ] },
>         { $lte: [ "$$num", NumberLong("9223372036854775807") ] }
>       ] }
>   }
> }

All in all, it is a big taskm but it would be great to have support for `$filter` implemented in Fongo.

**Comment by connollyst** [comment]
+1

**Comment by nicolaViola** [comment]
What does +1 mean?

**Comment by connollyst** [comment]
I would also like to see support for ``$filter`` in Fongo. We have aggregation queries using this new feature that are untestable with Fongo.
