### ISSUE TITLE
com.mongodb.BasicDBObject cannot be cast to java.util.Date

### ISSUE THREAD

**Issue by yamiveranes** [fakemongo/fongo#237]
I have an error when i try to execute two projections:

**java.lang.ClassCastException: com.mongodb.BasicDBObject cannot be cast to java.util.Date**

The aggregation looks like :

db.search.aggregate(
[
            { 
                   "$project" :  
                   {
                                     "date" : {  "$add" : [  "$date" , -14400000 ]  }
                    }
            } , 
            {
                   "$project" : 
                    { 
                                      "yearDate" :  {  "$year"  :  [  "$date" ] } ,
                                      "monthDate" : { "$month" : [ "$date" ] }
                     }
            }
]
)

The same query works in mongo shell.

**Comment by twillouer** [comment]
can you test against master ?
