### ISSUE TITLE
The _id field not returned for collections with name starting with "system"

### ISSUE THREAD

**Issue by theimplementer** [fakemongo/fongo#242]
This is due to the logic implemented in the FongoDBCollection class. The _id field for documents contained in a collection named with system\* is removed when they're returned.

``` java
    @Test
    public void testId() throws Exception {
        final Fongo fongo = new Fongo("test");
        final MongoDatabase database = fongo.getDatabase("test-db");
        final MongoCollection<Document> systemUsers = database.getCollection("systemUsers");
        final UUID id = UUID.randomUUID();
        final Document document = new Document("_id", id);
        systemUsers.insertOne(document);
        final Document retrievedDocument = systemUsers.find().iterator().next();

        assertThat(retrievedDocument.get("_id", UUID.class), is(id));
    }
```

A solution to this could be checking if the name of the collection starts with "system." (with the extra .)

**Comment by nicolaViola** [comment]
Hi,
I tryed to fix the issue like you say but it did't cover all name collection name. So I added a collection name validation in insertCommand. (FongoConection.class). I hope it could be enough. I did a pull request, so I am waitng for it.
Best regards
Nicola
