### ISSUE TITLE
NoSuchMethodError getReadConcern()

### ISSUE THREAD

**Issue by ddperdue** [fakemongo/fongo#243]
I am having trouble getting this to work with my project. I am using mongo-java-driver 3.3 and Fongo 2.0.9, but when I use the @Rule in my tests as documented in the read me I get this error.

```
java.lang.NoSuchMethodError: com.mongodb.MongoClientOptions.getReadConcern()Lcom/mongodb/ReadConcern;

	at com.mongodb.MockMongoClient.create(MockMongoClient.java:32)
	at com.github.fakemongo.Fongo.createMongo(Fongo.java:159)
	at com.github.fakemongo.Fongo.<init>(Fongo.java:75)
	at com.github.fakemongo.junit.FongoRule.newFongo(FongoRule.java:212)
	at com.github.fakemongo.junit.FongoRule.<init>(FongoRule.java:66)
	at com.github.fakemongo.junit.FongoRule.<init>(FongoRule.java:75)
	at com.github.fakemongo.junit.FongoRule.<init>(FongoRule.java:71)
```

I have tried various versions of the mongo-java-driver but all produce the same error.

**Comment by nicolaViola** [comment]
Hi, 
I have created a junit test that uses @Rule

`@Rule
    public FongoRule fongoRule = new FongoRule();`

`@Test
    public void test_doSomething() {
	...
    }`

but I didn't receive any exception and the before and after methods work well when I debug FongoRule.
I am using mongo-java-driver3.3 and the just downloaded Fongo version source .

Do you mind giving more information please?
I am looking forward to hearing from you soon 

Best regards
Nicola

**Comment by ddperdue** [comment]
Thank you for looking into this Nicola. I have my test set up the same as you have above and I am still getting this error. Here are the relevant dependencies I have added to the project. 
```
<dependency>
    <groupId>org.mongodb</groupId>
    <artifactId>mongo-java-driver</artifactId>
    <version>3.3.0</version>
    <type>jar</type>
</dependency>
<dependency>
    <groupId>com.github.fakemongo</groupId>
    <artifactId>fongo</artifactId>
    <version>2.0.9</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>ch.qos.logback</groupId>
    <artifactId>logback-classic</artifactId>
    <version>1.1.1</version>
    <scope>test</scope>
</dependency>
```
I'm not sure what other details would help. We are not using sl4j in our project so I had to add the logback dependency as detailed in the readme. Not sure if that could cause this issue somehow. Let me know if there is anything else I could provide that would help. Thank you again for looking into it.

**Comment by nicolaViola** [comment]
Hi,
I would like to know what happens if you use another version of logBack, for example

```
<dependency>
	    <groupId>ch.qos.logback</groupId>
	    <artifactId>logback-classic</artifactId>
	    <version>1.1.3</version>
	    <scope>test</scope>
</dependency>   
```
Actually I have a trouble with my eclipse project if I use the 1.1.1 version (The project cannot be built until build path errors are resolved) but if I change version to 1.1.3 evrything works.
Thank you in advance

**Comment by ddperdue** [comment]
I updated the logback dependency to 1.1.3 like you have here, but I am still getting the same error. I'm sure it is something I'm doing wrong but I can't figure out what it is.

**Comment by nicolaViola** [comment]
Do you mind sending your test class please?

**Comment by ddperdue** [comment]
I think we have tracked down our issue. There is another dependency in our project that has mongo-java-driver as a dependency. It is using t 3.0.2. Somehow that is the one that is getting used instead of the 3.3.0 version that I have added directly to the project. I haven't sorted out exactly how to fix it yet but am pretty sure that is the problem. Thank you very much for your help.
