### ISSUE TITLE
Fongo throws exception when supplied with Long values for sort order and $size

### ISSUE THREAD

**Issue by amogh-hs** [fakemongo/fongo#256]
I use Fongo with Clojure.

Default type for a numeric integral constants in Clojure is java.lang.Long
So when we provide -1 or 1 for sort order to specify ascending or descending as the criteria, it tries to typecast that to Integer and throws a ``` ClassCastException ``` 

Also for $size, If you provide Long types, you get 

```
com.github.fakemongo.FongoException: $size clause expected to be of type java.lang.Integer but is class java.lang.Long

```

**Comment by twillouer** [comment]
Hi,

can you check against master ?
