### ISSUE TITLE
$$ROOT is not working in aggregation

### ISSUE THREAD

**Issue by bhliva** [fakemongo/fongo#259]
I have a query: 
[{$match : {}}, {$group : {"_id" : {"test1" : "$Test1"},"document" :{"$first" : "$$ROOT"}}}]

returns me NULL in "document" field

**Comment by zouyonghao** [comment]
Same here.

**Comment by scorpp** [comment]
behaviour is same for `last`, `push` as well

**Comment by twillouer** [comment]
Hi,

can you test against master ?
