### ISSUE TITLE
Lookup joined on ObjectId fails with ClassCastException

### ISSUE THREAD

**Issue by krs** [fakemongo/fongo#260]
Lookup.java in `performLookup` method casts join field to String, this fails if the field is for example an ObjectId.

**Comment by moisko** [comment]
Bonjour twillouer,
Ce commit en fait est un fix qui nous est necessaire pour nos tests d'integration. Est-il possible que la version 2.0.11 contient ce fix est plus precisement quand vous allez faire release?

Cordialement, Boris

**Comment by twillouer** [comment]
version 2.0.12 out :)

**Comment by moisko** [comment]
merci!
