### ISSUE TITLE
Cannot create collection

### ISSUE THREAD

**Issue by livthomas** [fakemongo/fongo#272]
I am trying to create a collection using Fongo 2.0.12 and I always get the following exception:

```
com.github.fakemongo.FongoException: Not implemented for command : { "create" : "collectionUpdateDocument" , "capped" : false}
```

Does not Fongo support such a basic command as creating a collection? How am I supposed to write any test without it?

**Comment by amandeep009** [comment]
Rather than create collection you should use :  db.getCollection("CollectionName");
