### ISSUE TITLE
Support for $all operator?

### ISSUE THREAD

**Issue by avk2** [fakemongo/fongo#286]
Does fongo support `$all` operator?

I couldn't use it on a MongoRepository with @Query: https://stackoverflow.com/questions/44548170/how-do-i-pass-an-array-to-a-mongorepository-query/44560911

Btw, switching to real mongo with:
```
@Rule
public FongoRule fongoRule = new FongoRule("meh",true);
```
didn't work. I've had to discard all the fongo configuration.

**Comment by nielsfalk** [comment]
It does!

**Comment by twillouer** [comment]
thanks :)
