### ISSUE TITLE
buildInfo command Not implemented

### ISSUE THREAD

**Issue by luan-cestari** [fakemongo/fongo#339]
Hi,

I was doing some tests using fongo and I caught a exception in my log "FongoException("Not implemented for command ...".

I will create a PR to add this command. Not sure if you guys will mind the static json or have some advice.

I would also add mvnw to the project if you allow me

**Comment by stefanbirkner** [comment]
This command is executed by Spring Boot's [MongoHealthIndicator](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/mongo/MongoHealthIndicator.java). It's not possible to write proper tests as long as this command cannot be executed.

**Comment by twillouer** [comment]
thanks  @luan-cestari

**Comment by stefaneicher** [comment]
could you release this feature? or when is the next release planned?

**Comment by gandikota101** [comment]
When is this fix planned to be released?
