### ISSUE TITLE
Cannot use fongo in OSGi environment

### ISSUE THREAD

**Issue by lichtin** [fakemongo/fongo#75]
Would be great to make it usable also within OSGi container.
For this to work, only two changes are needed, I believe:

 - Use maven-bundle-plugin to enrich the MANIFEST.MF
				<plugin>
					<groupId>org.apache.felix</groupId>
					<artifactId>maven-bundle-plugin</artifactId>
					<version>2.4.0</version>
				</plugin>
 - avoid using package 'com.mongodb', i.e. move the 3 classes to another package

**Comment by twillouer** [comment]
@lichtin any news ?

**Comment by lichtin** [comment]
Sorry I didn't pursue this any further. Using fongo only outside of OSGi currently.
