### ISSUE TITLE
Querying indexed field in subdocument does not work, but works without index

### ISSUE THREAD

**Issue by tkruse** [fakemongo/fongo#76]
Hi,

On a collection like this:

```
{
        "_id" : ObjectId("547f0f7c44ae106a17c478ff"),
        "_class" : "com.example.Example",
        "version" : NumberLong(0),
        "randomIds" : {
                "randomIds" : [
                        {
                                "value" : "test1234",
                                "language" : "de"
                        }
                ]
        }
```

with an index on the subdocument field like this (and other indexes):

```
        {
                "v" : 1,
                "unique" : true,
                "key" : {
                        "randomIds.randomIds.value" : 1
                },
                "name" : "randomIds.randomIds.value",
                "ns" : "mydb.com.example",
                "sparse" : true
        }
```

The following query returns null:
`{"randomIds.randomIds.value" : "test1234"}}`

But when I remove the index, the same query returns the document.

I cannot tell whether this is covered by the disclaimer of missing MongoDB features, or a bug. If you tell me it is likely a bug, I can put in more effort to reproduce.

**Comment by nitram509** [comment]
@joshcanfield I did run the above regression test on 2.2.0-rc2 -- the rest result is green.
I recommend creating a new issue with reference to this (instead of re-open this).
But more importantly, may I ask for some more context or test-snippet? Just "it seems ...." is not that much convincing to dig deeper ;)
