### ISSUE TITLE
Provide Java Configuration (annotation-driven) example

### ISSUE THREAD

**Issue by massenz** [fakemongo/fongo#86]
Thanks for creating fongo!

It would be great if you could provide the configuration example via Java configuration (``@Configuration``) alongside the XML bean configs.

We don't use XML to configure our app context (in fact, use Spring Boot) and I'd like to use Fongo, but right now, it's not obvious how to do so.

Also, please consider adding an example using Spring's Profiles (``@Profile("test")`` for example).

The project I'd like to use it with is [Spring-Template](https://github.com/massenz/spring-template)

Thanks!

**Comment by twillouer** [comment]
Something like that ? (see #92)

```java
  @Configuration
  @EnableMongoRepositories
  public static class FongoConfig extends AbstractMongoConfiguration {

    @Override
    protected String getDatabaseName() {
      return "FongoDB";
    }

    @Override
    public Mongo mongo() throws Exception {
      return new Fongo(getDatabaseName()).getMongo();
    }

  }
```
