### ISSUE TITLE
DBCollection.drop() removes indexes on other collections.

### ISSUE THREAD

**Issue by wbdarby** [fakemongo/fongo#91]
Using a database with 2 collections, each having 1 index (in addition to the "_id") index.
Drop the second collection, and call DBCollection.getIndexInfo() on the first collection. It will return a single index (the non-"_id" index having been removed).

Looking at the source this appears to be due to FongoDBCollection._dropIndexes() does not filter the indexes based on the collection namespace: 
final List<DBObject> indexes = fongoDb.getCollection("system.indexes").find().toArray();

Contrast this with the MongoDB Java source for determining the index's collections in DBCollection.getIndexInfo():
  ...
  BasicDBObject cmd = new BasicDBObject();
  cmd.put("ns", getFullName());

  DBCursor cur = _db.getCollection("system.indexes").find(cmd);

**Comment by twillouer** [comment]
Right, Thanks !
