### ISSUE TITLE
AbstractMethodError with Fongo 1.5.10 shadowing v 2.13 of the Mongo Java driver

### ISSUE THREAD

**Issue by colmmcdonnell** [fakemongo/fongo#95]
I'm getting an AbstractMethodError when calling DBCollection.getIndexInfo() ...

````
java.lang.AbstractMethodError: com.mongodb.DBCollection.getIndexInfo()Ljava/util/List;
````

Setup, versions etc as follows:

* Fongo: 1.5.10 
* Mongo Java Driver: 2.13.0-rc2

Reproduction case:

````
    @Test(expected = AbstractMethodError.class)
    public void showMongoFongoIncompatibility() {
        DBCollection collection = mongo.getDB(databaseName).getCollection(collectionName);
        
        collection.getIndexInfo();
    }
````

If I downgrade my mongo-java-driver to 2.12.5 (i.e. the vesion of the Java driver against which Fongo 1.5.10 was built) then the problem disappears so this looks like an incompatability between Fongo 1.5.10 and Mongo's 2.13 Java driver.

**Comment by twillouer** [comment]
Yes, the next version will take care of this, but I have many other problem.

I try to release it tomorrow

**Comment by colmmcdonnell** [comment]
Thanks, much appreciated.

**Comment by twillouer** [comment]
@colmmcdonnell you can check against the v2_13 branch (doesn't pass unittest for now)
(mvn clean install -DskipTests) and upgrade your pom, I hope this work :)

**Comment by colmmcdonnell** [comment]
@twillouer will do, thanks

**Comment by colmmcdonnell** [comment]
@twillouer I built a JAR from the v2_13 branch and re ran my test suite, I can confirm that the issue is resolved with the v2_13 branch. 

Can you let me know when 1.5.11 (or whatever version it will be released as) might be available on maven central?

Thanks for your help.

**Comment by twillouer** [comment]
hi @colmmcdonnell, fongo 1.6.0 will be published in few hours

**Comment by colmmcdonnell** [comment]
@twillouer, got it and can confirm that the upgrade is working for me, thanks again.
